### ISSUE TITLE
Revit 2015 not showing Sync times

### ISSUE THREAD

**Issue by pderooy** [pix3lot/Slackit#11]
Hello
I downloaded the zip and setup a Slack account.
I got it all installed and can send a screenshot to slack but when I sync to central it does not send anything to Slack.

any ideas?

Thanks

**Comment by pix3lot** [comment]
Did you have the messages enabled in the settings? Check the "Info" box next to "Worksharing"

**Comment by pderooy** [comment]
Yes,
I tried it with many combinations.

**Comment by pix3lot** [comment]
Its hard to tell what would be going on in your specific case. It should work with those options enabled. Before unzipping did you unblock the Zip file? If not, you can unblock the DLL files in the folder. If that's not the issue, are you able to debug and step through the code, then you would be able to tell where the issue is.

**Comment by pix3lot** [comment]
@pderooy @djsiroky I just noticed why this is happening. The issue is that you must have at least one pinned element for the notifications to work. This is an issue we need to fix in the code, but pinning one element in Revit will work around the issue for now.
