### ISSUE TITLE
I found a part of my slackit that was giving me a null and not letting me see my syncs. 

### ISSUE THREAD

**Issue by dannysbentley** [pix3lot/Slackit#13]
here is what I changed to get it to work.  EventsApplication.cs Line 280

`Dictionary<int, string> end_state = TrackChanges.Command.GetSnapshot(a);
            _start_state = TrackChanges.Command.GetSnapshot(a);// I Moved here
            string results = TrackChanges.Command.ReportDifferences(doc, _start_state, end_state);
            //_start_state = TrackChanges.Command.GetSnapshot(a);`

**Comment by djsiroky** [comment]
Were you having the same issue as issue #11? If so, downloading the most recent version from here might resolve the issue.

The only problem I an see with changing the code to be:
```
Dictionary<int, string> end_state = TrackChanges.Command.GetSnapshot(a);
_start_state = TrackChanges.Command.GetSnapshot(a);
string results = TrackChanges.Command.ReportDifferences(doc, _start_state, end_state);
```

instead of:

```
Dictionary<int, string> end_state = TrackChanges.Command.GetSnapshot(a);
string results = TrackChanges.Command.ReportDifferences(doc, _start_state, end_state);
_start_state = TrackChanges.Command.GetSnapshot(a);
```

would be that the start and end states would be the same when the ReportDifferences function is called, so it would never report any pinned or unpinned items. Let me know if I misread your code though or if the issue still persists with the latest version.

**Comment by dannysbentley** [comment]
I will download the new one, but the null in _start_state caused the program to exit out and not send the payload to slack.

**Comment by djsiroky** [comment]
Ah, you're absolutely correct. _start_state is initially set here: https://github.com/pix3lot/Slackit/blob/master/SlackitRevit/EventsApplication.cs#L226 but that's not always hit (for example, if Slack is not enabled when the document is opened), which would mean it's still null and cause the problems you're seeing.

It may be as simple as moving it up to around lines 49-77, so that initiate snapshot is always taken, even if it's not used. But I'll also look into better error handling in the ReportDifferences method.
