### ISSUE TITLE
Slack it 2016 Plugin not working

### ISSUE THREAD

**Issue by helenaqr** [pix3lot/Slackit#16]
Hello! Id instaled the plugin but its not working,  Ive placed it in the fold ( inside and outside a fold -  image 3 when i do this- and then in complements appears image 4) but theres nothing in complements when I open Revit. What is failing? 
Thank you!

![dfdsfsd](https://user-images.githubusercontent.com/32513512/31174401-b3a03d80-a90b-11e7-96ef-295cc3c86a16.JPG)
![fdsfds](https://user-images.githubusercontent.com/32513512/31174438-d1b09824-a90b-11e7-9529-f5398512f39f.JPG)
![ertte](https://user-images.githubusercontent.com/32513512/31174686-b8c76526-a90c-11e7-9536-a5d889e5115e.JPG)
![dasasda](https://user-images.githubusercontent.com/32513512/31174744-e221441e-a90c-11e7-922f-8a4c1b32dc7a.JPG)

**Comment by djsiroky** [comment]
Hi @helenaqr, I followed the same steps as you and got the same problem. So I went ahead and rebuilt the zip folders and opened a pull request. If you'd like to try before the changes are brought it, you can download the 2016 zip file [from here](https://github.com/djsiroky/Slackit/blob/1c518445708db508508e93d0e47c4a70ce2a7168/SlackIt-2016.zip). Otherwise you can download it from here, once it is merged!

Thanks,
Dan

**Comment by pix3lot** [comment]
I'm closing this as I assume it was fixed.
